
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.setuptools]
packages = ["pystarter"]
package-dir = {"" = "src"}
include-package-data = true


[project.scripts]
pystarter = "pystarter:main"

[tool.pip-tools]
generate-hashes = true


dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "pystarter.version.VERSION"}
readme = {file = ["README.md"]}
