# MIT License

# # Copyright (c) 2024 Aaron Saikovski

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# https://taskfile.dev

version: "3"


###############################################################################

tasks:
  ## default - Default cmd - create
  default:
    deps: [create]
    desc: "Call Create as default cmd."

  ###########################################################################

  ## create - Inits the poetry virtual environment and installs baseline packages
  create:
    desc: "Inits the python project using UV and creates and activates a new virtual environment."
    cmds:
      - uv init
      - uv venv

  ###########################################################################

  ## deps - Install the dependencies
  deps:
    desc: "Install the dependencies."
    deps: [activate]
    cmds:
      - uv add pytest pytest-cov isort black ruff bandit pyinstaller
      - uv tool upgrade --all

  ###########################################################################

  ## activate - Activates the virtual environment
  activate:
    desc: "Activates the virtual environment."
    cmds:
      - .venv\\Scripts\\activate

  ###########################################################################

  ## run - Run the script main.py
  run:
    desc: "Run the script main.py"
    deps: [activate]
    cmds:
      - uv run -m pystarter

  ###########################################################################

  # clean - Cleans the environment, Overwrites the pyproject.toml file
  clean:
    desc: "Cleans the environment, Overwrites the pyproject.toml file"
    cmds:
      - cmd /c "rmdir /s /q .venv"
      - cmd /c "rmdir /s /q .ruff_cache"
      - cmd /c "rmdir /s /q .pytest_cache"
      - cmd /c "del /q .python-version"
      - cmd /c "del /q uv.lock"
      - cmd /c "del /q pyproject.toml"


  #############################################################################

  ## test - Tests the project
  test:
    desc: "Tests the project."
    deps: [activate]
    cmds:
      - uv tool run pytest

  ###########################################################################

  ## update - updates dependency versions
  update:
    desc: "updates dependency versions"
    deps: [activate]
    cmds:
      - uv tool upgrade --all

  ###########################################################################

  ## lint - Lints the project using ruff --fix and sorts imports using isort
  lint:
    desc: "Lints the project using ruff --fix and sorts imports"
    deps: [activate]
    cmds:
      - uv tool run isort .
      #- uv tool run black .
      - uv tool run ruff check . --fix
     

  ###########################################################################

  ## vulncheck - Checks for vulnerabilities in the project
  vulncheck:
    desc: "Checks for vulnerabilities in the project"
    cmds:
      - uv tool run bandit -r .

  ###########################################################################

  ## release - uses pyinstaller to package your Python application into a single package
  release:
    desc: "uses pyinstaller to package your Python application into a single package"
    deps: [activate]
    cmds:
      - uv tool run pyinstaller main.py

  ###############################################################################

  ## docker-build - builds a docker image based on the docker file
  docker-build:
    desc: "builds a docker image based on the docker file"
    deps: [deps]
    cmds:
      - docker build -t $PROJECT_NAME:latest .

  ###############################################################################

  ## docker-run - runs the docker container
  docker-run:
    desc: "builds a docker image based on the docker file"
    #deps: [docker-build]
    cmds:
      - docker run $PROJECT_NAME:latest

  ###############################################################################